name: Deploy Core API To dev

on:
  push:
    branches: [dev]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{secrets.SSH_HOST}}
          USER_NAME: ${{secrets.USER_NAME}}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

              # Now we have got the access of EC2 and we will start the deploy .
              cd /home/ubuntu/apps/dev/Truwix-RM-Rental-Backend &&
              git pull &&
              npm install --force && 
              (pm2 restart "RM-Rental-Dev" || pm2 start npm --name "RM-Rental-Dev" -- run start:prod)
             '
